spring.application.name=osm-dev-io-server
spring.jpa.hibernate.ddl-auto=create
spring.session.jdbc.initialize-schema=always
spring.session.jdbc.table-name=SESSIONS
spring.session.jdbc.schema=classpath:session/schema-postgresql.sql